{% set name = "wagtailmenus" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtailmenus-{{ version }}.tar.gz
  sha256: d233dba4f67a72a19b61bfa0a494949e52622be124d8b537287d5d64021c57f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - wagtail >=5.2
    - django-cogwheels ==0.3

test:
  imports:
    - wagtailmenus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/wagtailmenus/tree/stable/3.1.x
  summary: An app to help you manage menus in your Wagtail projects more consistently.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
