{% set name = "wagtailmenus" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jazzband/wagtailmenus/archive/v{{ version }}.tar.gz
  sha256: 1854e30c708cf494cf14182c1d4dfe07756548146dbaca36dc386e69c2c2eabe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=5.2
    - django-cogwheels ==0.3

test:
  imports:
    - wagtailmenus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jazzband/wagtailmenus/tree/stable/3.1.x
  summary: An app to help you manage menus in your Wagtail projects more consistently.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
