{% set name = "wagtailmenus" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://github.com/jazzband/wagtailmenus/archive/v{{ version }}.tar.gz
  sha256: 94c7cde0903b13613bd0a0c1c756d166e4693ffab9a5a339dd31b9b9dea3dc36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - requests
    - django
    - django-modelcluster
    - python >={{ python_min }}
    - wagtail >=7.0
    - django-cogwheels ==0.3

test:
  imports:
    - wagtailmenus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jazzband/wagtailmenus/tree/stable/3.1.x
  summary: An app to help you manage menus in your Wagtail projects more consistently.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
